### ISSUE TITLE
How to post a message and that is handled by one subscriber only

### ISSUE THREAD

**Issue by CreativeManix** [rethinkdb/example-pubsub#7]
Could you please let me know if there is a way to publish a message, and that is handled by only one subscriber, even if there are multiple one waiting to process. I am looking to do background scalable background task executors, and I don't want same task is executed multiple times.

**Comment by danielmewes** [comment]
I don't think there's a way to do it directly, but you can get this effect as follows:
1. Send the message to every subscriber
2. Each subscriber issues a `table.get(id).delete()` on the message
3. Because single-document writes are atomic in RethinkDB, the `delete` will return `deleted: 1` for only one of the subscribers

Instead of a `delete`, you can also use other writes (`update`, `replace`) with a custom write function that checks that the message hasn't been "claimed" by another subscriber yet.

**Comment by deontologician** [comment]
@CreativeManix there isn't a way to do this with the strategy in this repository, since it relies on messages being ephemeral changefeed notifications, which can't be acknowledged.

But, you can simulate this by adding your jobs to a table, with roughly this structure:

```js
// r.table('jobs')
{
  id: jobId,
  job_definition: <whatever params you need>,
  started_on: null || Date,
  finished_on: null || Date
}
```
Then you'd have a changefeed on the `jobs` table for each worker:
```js
r.table('jobs').changes()
```

When a change comes in, the worker would try to claim it by setting the `started_on` field:

```js
r.table('jobs').get(jobId).update(job =>
  r.branch(job('started_on').ne(null),
    r.error('Another worker got the job'),
    job.merge({ started_on: r.now() })
  ))
```
